"""add ai fields to task

Revision ID: 70fceaa625f4
Revises: 685d753a8510
Create Date: 2026-06-07 16:39:45.996145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70fceaa625f4'
down_revision: Union[str, Sequence[str], None] = '685d753a8510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('ai_summary', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('ai_tags', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'ai_tags')
    op.drop_column('tasks', 'ai_summary')
    # ### end Alembic commands ###
