"""add ai fields to task

Revision ID: ad206af5ecbc
Revises: 70fceaa625f4
Create Date: 2026-06-07 16:42:55.021723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad206af5ecbc'
down_revision: Union[str, Sequence[str], None] = '70fceaa625f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('ai_difficulty', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'ai_tags',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'ai_tags',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('tasks', 'ai_difficulty')
    # ### end Alembic commands ###
